### ISSUE TITLE
Change in number of character classes

### ISSUE THREAD

**Issue by eg9** [Pomax/ucharclasses#16]
In TeX Live 2016, the number of allowed character classes has been increased to 4096, so a change is necessary.

I suggest changing the four existing `\@cclv` tokens into `\ucharclass@last` and to add an initialization like

    \@ifundefined{e@alloc@intercharclass@top}
      {\chardef\ucharclass@last=\@cclv}
      {\chardef\ucharclass@last=\e@alloc@intercharclass@top}

The rationale is that the updated LaTeX kernel will contain `\e@alloc@intercharclass@top` that will receive the correct value (255 or 4095 depending on whether XeTeX is up to version 0.99994 or later). In the case an older LaTeX kernel is used, the value 255 will be used.

**Comment by Pomax** [comment]
https://github.com/Pomax/ucharclasses/blob/master/ucharclasses.sty#L718 already defines it as 4095 now, with fallback for old XeTeX.
