### ISSUE TITLE
Miscellaneous Symbols and Pictographs range supprt?

### ISSUE THREAD

**Issue by wilx** [Pomax/ucharclasses#9]
Recently, I have come across the [Miscellaneous Symbols and Pictographs range (1F300–1F5FF)](http://www.unicode.org/charts/PDF/U1F300.pdf). I started looking around for how I could use it conveniently and found ucharclasses. Is it supported? I do not see it in the documented list of ranges.

**Comment by Pomax** [comment]
Current compatibility for ucharclasses is Unicode 6.0, where the range you found is one of the new Unicode 8.0 ranges, so technically: no, it's not supported. However, all the blocks are defined in https://github.com/Pomax/ucharclasses/blob/master/ucharclasses.sty#L32 so adding the new 7.0 and 8.0 blocks should be relatively straight forward (with possibly new/extended https://github.com/Pomax/ucharclasses/blob/master/ucharclasses.sty#L236)

**Comment by lemzwerg** [comment]
This is now available with version 2.2, to be found on CTAN since a few minutes (and on all mirrors within approx. 48h).

@pomax, please close.
